### ISSUE TITLE
Nothing appears on front end

### ISSUE THREAD

**Issue by zeddyblue** [riasvdv/statamic-lemon-squeezy#1]
Installed this according to your instructions. Linked to Lemon Squeezy without an issue. Modified Blueprint as required. Selected Product in statamic backend when editing the page. Nothing comes up on website. Am I missing a step somewhere? 

Kind regards
Zoran

**Comment by riasvdv** [comment]
You need to add the field to your template somewhere, like `{{ field_name }}`
